[package]
name = "basic_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Postgres interaction
postgres = "0.19.4"

codegen = { path = "basic_sync_codegen", package = "basic_sync_codegen" }
