[package]
edition = "2021"
name = "basic-async"
version = "0.1.0"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
deadpool-postgres = "0.10.3"
futures = "0.3.25"
postgres-types = { version = "0.2.4", features = ["derive"] }
tokio-postgres = "0.7.7"
cornucopia_async = { path = "../../clients/async" }
